Update patch set 1
Patch Set 1:

For some reason, these are now causing build errors for me.

prebuilts/gcc/linux-x86/arm/arm-linux-androideabi-4.9/arm-linux-androideabi/bin/ld: error: cannot find -llog
packages/apps/Gallery2/jni_jpegstream/src/jpegstream.cpp:320: error: undefined reference to '__android_log_print'
packages/apps/Gallery2/jni_jpegstream/src/jpegstream.cpp:320: error: undefined reference to '__android_log_print'
packages/apps/Gallery2/jni_jpegstream/src/jpegstream.cpp:329: error: undefined reference to '__android_log_print'
packages/apps/Gallery2/jni_jpegstream/src/jerr_hook.cpp:42: error: undefined reference to '__android_log_print'
clang++: error: linker command failed with exit code 1 (use -v to see invocation)

Patch-set: 1
Label: Verified=0